include $(THEOS)/makefiles/common.mk
BUNDLE_NAME = TopDownNotifications16Prefs
TopDownNotifications16Prefs_FILES = TDRootListController.m
TopDownNotifications16Prefs_FRAMEWORKS = UIKit Foundation CoreFoundation
TopDownNotifications16Prefs_PRIVATE_FRAMEWORKS = Preferences
TopDownNotifications16Prefs_CFLAGS = -fobjc-arc -Wall -Wextra -Wno-unused-parameter
TopDownNotifications16Prefs_INSTALL_PATH = /Library/PreferenceBundles
TopDownNotifications16Prefs_RESOURCE_DIRS = Resources
include $(THEOS_MAKE_PATH)/bundle.mk
